package dev.s7a.sqldelight.check.rules.hsql.rules

import dev.s7a.sqldelight.check.api.RuleId
import kotlin.test.Test
import kotlin.test.assertEquals

class HsqlRulesTest {
    @Test
    fun `reports database and file settings`() {
        val diagnostics =
            NoDatabaseFileSettingsRule().diagnostics(
                """
                SET DATABASE DEFAULT TABLE TYPE CACHED;
                SET FILES WRITE DELAY 10;
                """,
            )

        assertEquals(2, diagnostics.size)
        assertEquals(setOf(RuleId("hsql:no-database-file-settings")), diagnostics.map { it.ruleId }.toSet())
    }

    @Test
    fun `database and file settings ignore comments and quoted text`() {
        assertEquals(
            emptyList(),
            NoDatabaseFileSettingsRule().diagnostics(
                """
                -- SET DATABASE DEFAULT TABLE TYPE CACHED;
                INSERT INTO note VALUES ('SET FILES WRITE DELAY 10');
                """,
            ),
        )
    }

    @Test
    fun `reports system operations`() {
        NoSystemOperationsRule().assertOne("CHECKPOINT DEFRAG;")
        NoSystemOperationsRule().assertOne("BACKUP DATABASE TO 'backup.tar.gz' BLOCKING;")
        NoSystemOperationsRule().assertOne("PERFORM EXPORT SCRIPT FOR DATABASE STRUCTURE TO 'schema.sql';")
    }

    @Test
    fun `reports text table file sources`() {
        NoTextTableSourceRule().assertOne(
            """
            CREATE TEXT TABLE player (id BIGINT PRIMARY KEY, name VARCHAR(128));
            """,
        )
        NoTextTableSourceRule().assertOne(
            """
            SET TABLE player SOURCE 'player.csv;fs=,';
            """,
        )
    }

    @Test
    fun `accepts ordinary schema changes`() {
        assertEquals(
            emptyList(),
            NoTextTableSourceRule().diagnostics(
                """
                CREATE TABLE player (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(128) NOT NULL
                );
                """,
            ),
        )
    }
}
