package dev.s7a.sqldelight.check.rules.hsql.rules

import kotlin.test.Test
import kotlin.test.assertEquals

class NoTextTableSourceRuleTest {
    @Test
    fun `reports text table file sources`() {
        NoTextTableSourceRule().assertOne(
            """
            CREATE TEXT TABLE player (id BIGINT PRIMARY KEY, name VARCHAR(128));
            """,
        )
        NoTextTableSourceRule().assertOne(
            """
            SET TABLE player SOURCE 'player.csv;fs=,';
            """,
        )
    }

    @Test
    fun `accepts ordinary schema changes`() {
        assertEquals(
            emptyList(),
            NoTextTableSourceRule().diagnostics(
                """
                CREATE TABLE player (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(128) NOT NULL
                );
                """,
            ),
        )
    }
}
