package dev.s7a.sqldelight.check.rules.standard.rules

internal val commonSqlFunctions: Set<String> =
    setOf(
        "abs",
        "avg",
        "coalesce",
        "count",
        "date",
        "datetime",
        "group_concat",
        "hex",
        "ifnull",
        "instr",
        "json_extract",
        "length",
        "lower",
        "ltrim",
        "max",
        "min",
        "nullif",
        "random",
        "replace",
        "round",
        "rtrim",
        "strftime",
        "substr",
        "substring",
        "sum",
        "time",
        "trim",
        "typeof",
        "upper",
    )
